CORE-1149 add check error

diff --git a/template/dbms/postgresql/init/init_schema b/template/dbms/postgresql/init/init_schema
--- a/template/dbms/postgresql/init/init_schema
+++ b/template/dbms/postgresql/init/init_schema
@@ -51,12 +51,17 @@ function replaceFn {
     sed -i -e "$rem1" -e "$rem2" -e "$rem3" -e "$rem4" -e "$rem5" -e "$rem6" -e "$rem7" -e "$rem8" -e "$rem9" -e "$rem10" -e "$rem11" "$1"
 }
 
-commadLiquibase="$DIR/../liquibase/liquibase --username=$sPw --password=$sUser --url=$connectionPreBd --driver=org.postgresql.Driver --changeLogFile=db.changelog.init.xml update"
-
-$commadLiquibase
-
 replaceFn "$DIR/db.sql"
 replaceFn "$DIR/db.changelog.init.xml"
+
+commadLiquibase="$DIR/../liquibase/liquibase --username=$sPw --password=$sUser --url=$connectionPreBd --driver=org.postgresql.Driver --changeLogFile=db.changelog.init.xml update"
+cd $DIR
+$commadLiquibase
+if [ $? != 0 ]; then
+    echo "Error init $newDataBase errorcode $?"
+    exit 1
+fi
+
 replaceFn "$DIR/../db.changelog.meta.xml"
 replaceFn "$DIR/../db.changelog.schema.xml"
 replaceFn "$DIR/../liquibase.meta.properties"
